"""
混合渲染器与现有系统的集成示例
展示如何在现有内容生成流程中使用混合渲染
"""
import asyncio
import logging
from typing import Dict, Any, Optional

from api.services.advanced_content_generator import AdvancedContentGenerator
from api.services.hybrid_renderer import HybridRenderer, RenderConfig
from api.prompts.infographic_styles import STYLE_LIBRARY, DEFAULT_STYLE_ID

logger = logging.getLogger(__name__)


class InfographicWorkflow:
    """信息图生成工作流 - 集成混合渲染"""

    def __init__(self, redis_client=None):
        """
        初始化工作流

        Args:
            redis_client: Redis 客户端（可选）
        """
        self.content_generator = AdvancedContentGenerator()
        self.renderer = HybridRenderer(redis_client)
        logger.info("✅ InfographicWorkflow initialized")

    async def generate_complete_infographic(
        self,
        topic: str,
        style_id: str = DEFAULT_STYLE_ID,
        quality: str = "advanced",
        use_ai_background: bool = True
    ) -> Dict[str, Any]:
        """
        生成完整的信息图（内容 + 渲染）

        Args:
            topic: 主题
            style_id: 风格ID（从 STYLE_LIBRARY 中选择）
            quality: 质量等级 (normal/advanced/professional)
            use_ai_background: 是否使用AI生成背景

        Returns:
            包含SVG内容和元数据的字典
        """
        try:
            logger.info(f"🎨 Starting infographic generation for: {topic}")

            # 1. 生成内容
            logger.info("📝 Step 1: Generating content...")
            content_result = await self._generate_content(topic, quality)

            # 2. 转换为渲染格式
            logger.info("🔄 Step 2: Converting to render format...")
            content_data = self._convert_to_render_format(content_result)

            # 3. 获取风格配置
            logger.info("🎨 Step 3: Applying style configuration...")
            style_config = self._get_style_config(style_id, use_ai_background, topic)

            # 4. 渲染SVG
            logger.info("🖼️  Step 4: Rendering SVG...")
            svg_content = await self.renderer.render(content_data, style_config)

            logger.info("✅ Infographic generation completed!")

            return {
                "success": True,
                "svg": svg_content,
                "metadata": {
                    "topic": topic,
                    "style_id": style_id,
                    "quality": quality,
                    "svg_size": len(svg_content),
                    "content_sections": len(content_data.get("sections", []))
                }
            }

        except Exception as e:
            logger.error(f"❌ Infographic generation failed: {e}", exc_info=True)
            return {
                "success": False,
                "error": str(e),
                "svg": None
            }

    async def _generate_content(
        self,
        topic: str,
        quality: str
    ) -> Dict[str, Any]:
        """生成内容"""
        # 使用现有的内容生成器
        # 这里简化处理，实际需要调用 AdvancedContentGenerator 的方法

        # 模拟内容生成结果
        return {
            "title": topic,
            "subtitle": f"关于{topic}的深度解析",
            "sections": [
                {
                    "title": "核心概念",
                    "content": f"{topic}是一个重要的概念，它涉及多个方面的内容。"
                },
                {
                    "title": "关键要点",
                    "content": "理解这个主题需要掌握几个关键要素。"
                },
                {
                    "title": "实践应用",
                    "content": "在实际应用中，这个概念发挥着重要作用。"
                }
            ],
            "footer": "Generated by Avery System"
        }

    def _convert_to_render_format(
        self,
        content_result: Dict[str, Any]
    ) -> Dict[str, Any]:
        """将内容生成结果转换为渲染格式"""
        return {
            "title": content_result.get("title", ""),
            "subtitle": content_result.get("subtitle", ""),
            "sections": content_result.get("sections", []),
            "footer": content_result.get("footer", "")
        }

    def _get_style_config(
        self,
        style_id: str,
        use_ai_background: bool,
        theme: str
    ) -> Dict[str, Any]:
        """获取风格配置"""
        # 从风格库中提取配置
        style_text = STYLE_LIBRARY.get(style_id, STYLE_LIBRARY[DEFAULT_STYLE_ID])

        # 解析风格文本，提取颜色配置
        config = {
            "width": 1200,
            "height": 1600,
            "use_ai_background": use_ai_background,
            "theme": theme,
            "background_color": "#F7F4EF",
            "primary_color": "#2D5A3D",
            "secondary_color": "#C9A65C",
            "text_color": "#1F2328"
        }

        # 根据风格ID调整配置
        if style_id == "lab_manual_pop":
            config.update({
                "background_color": "#F2F2F2",
                "primary_color": "#B8D8BE",
                "secondary_color": "#E91E63",
                "text_color": "#2D2926"
            })
        elif style_id == "blueprint_pop_lab":
            config.update({
                "background_color": "#F2F2F2",
                "primary_color": "#B8D8BE",
                "secondary_color": "#E91E63",
                "text_color": "#2D2926"
            })
        elif style_id == "editorial_cards":
            config.update({
                "background_color": "#F6F1E9",
                "primary_color": "#2D5A3D",
                "secondary_color": "#C9A65C",
                "text_color": "#1F2328"
            })

        return config

    async def close(self):
        """关闭资源"""
        # 注意：AdvancedContentGenerator 不需要关闭
        await self.renderer.close()


class BatchInfographicGenerator:
    """批量信息图生成器"""

    def __init__(self, redis_client=None):
        """
        初始化批量生成器

        Args:
            redis_client: Redis 客户端（可选）
        """
        self.redis_client = redis_client
        self.workflow = InfographicWorkflow(redis_client)
        logger.info("✅ BatchInfographicGenerator initialized")

    async def generate_batch(
        self,
        topics: list[str],
        style_id: str = DEFAULT_STYLE_ID,
        quality: str = "advanced",
        use_ai_background: bool = True
    ) -> list[Dict[str, Any]]:
        """
        批量生成多个主题的信息图

        Args:
            topics: 主题列表
            style_id: 风格ID
            quality: 质量等级
            use_ai_background: 是否使用AI背景

        Returns:
            生成结果列表
        """
        results = []

        for i, topic in enumerate(topics, 1):
            logger.info(f"📊 Processing {i}/{len(topics)}: {topic}")

            try:
                result = await self.workflow.generate_complete_infographic(
                    topic=topic,
                    style_id=style_id,
                    quality=quality,
                    use_ai_background=use_ai_background
                )
                results.append(result)

            except Exception as e:
                logger.error(f"❌ Failed to generate infographic for '{topic}': {e}")
                results.append({
                    "success": False,
                    "topic": topic,
                    "error": str(e)
                })

        logger.info(f"✅ Batch generation completed: {len([r for r in results if r['success']])}/{len(topics)} successful")

        return results

    async def close(self):
        """关闭资源"""
        await self.workflow.close()


# 使用示例
async def example_single_infographic():
    """生成单个信息图的示例"""
    workflow = InfographicWorkflow()

    try:
        result = await workflow.generate_complete_infographic(
            topic="人工智能在医疗领域的应用",
            style_id="executive_clean",
            quality="advanced",
            use_ai_background=True
        )

        if result["success"]:
            # 保存SVG文件
            output_file = "/Users/wanting/program/CC/Avery/ai_medical_infographic.svg"
            with open(output_file, 'w', encoding='utf-8') as f:
                f.write(result["svg"])

            print(f"✅ Infographic saved to: {output_file}")
            print(f"📊 Metadata: {result['metadata']}")
        else:
            print(f"❌ Generation failed: {result['error']}")

    finally:
        await workflow.close()


async def example_batch_infographics():
    """批量生成信息图的示例"""
    generator = BatchInfographicGenerator()

    topics = [
        "区块链技术的发展趋势",
        "5G技术的商业应用",
        "云计算的安全挑战",
        "物联网的未来展望"
    ]

    try:
        results = await generator.generate_batch(
            topics=topics,
            style_id="executive_clean",
            quality="advanced",
            use_ai_background=False  # 批量时禁用AI以加快速度
        )

        # 保存结果
        successful_count = 0
        for i, result in enumerate(results):
            if result["success"]:
                successful_count += 1
                filename = f"/Users/wanting/program/CC/Avery/infographic_{i+1}.svg"
                with open(filename, 'w', encoding='utf-8') as f:
                    f.write(result["svg"])
                print(f"✅ Saved: {filename}")

        print(f"\n📊 Batch summary: {successful_count}/{len(topics)} successful")

    finally:
        await generator.close()


async def example_style_comparison():
    """比较不同风格的示例"""
    workflow = InfographicWorkflow()

    topic = "机器学习基础入门"
    style_ids = ["executive_clean", "lab_manual_pop", "editorial_cards"]

    try:
        for style_id in style_ids:
            print(f"\n🎨 Generating with style: {style_id}")

            result = await workflow.generate_complete_infographic(
                topic=topic,
                style_id=style_id,
                quality="advanced",
                use_ai_background=False
            )

            if result["success"]:
                filename = f"/Users/wanting/program/CC/Avery/style_comparison_{style_id}.svg"
                with open(filename, 'w', encoding='utf-8') as f:
                    f.write(result["svg"])
                print(f"✅ Saved: {filename}")

    finally:
        await workflow.close()


# FastAPI 集成示例
"""
from fastapi import APIRouter, HTTPException
from api.services.hybrid_renderer_integration import InfographicWorkflow

router = APIRouter()

@router.post("/api/generate-infographic")
async def generate_infographic_api(request: dict):
    '''生成信息图 API'''
    topic = request.get("topic")
    style_id = request.get("style_id", "executive_clean")
    quality = request.get("quality", "advanced")
    use_ai_background = request.get("use_ai_background", True)

    if not topic:
        raise HTTPException(status_code=400, detail="Topic is required")

    workflow = InfographicWorkflow()
    try:
        result = await workflow.generate_complete_infographic(
            topic=topic,
            style_id=style_id,
            quality=quality,
            use_ai_background=use_ai_background
        )

        if not result["success"]:
            raise HTTPException(status_code=500, detail=result["error"])

        return {
            "svg": result["svg"],
            "metadata": result["metadata"]
        }

    finally:
        await workflow.close()


@router.post("/api/batch-generate-infographics")
async def batch_generate_infographics_api(request: dict):
    '''批量生成信息图 API'''
    topics = request.get("topics", [])
    style_id = request.get("style_id", "executive_clean")
    quality = request.get("quality", "advanced")
    use_ai_background = request.get("use_ai_background", False)

    if not topics:
        raise HTTPException(status_code=400, detail="Topics list is required")

    generator = BatchInfographicGenerator()
    try:
        results = await generator.generate_batch(
            topics=topics,
            style_id=style_id,
            quality=quality,
            use_ai_background=use_ai_background
        )

        return {
            "results": results,
            "summary": {
                "total": len(results),
                "successful": len([r for r in results if r["success"]]),
                "failed": len([r for r in results if not r["success"]])
            }
        }

    finally:
        await generator.close()
"""


if __name__ == "__main__":
    # 运行示例
    import asyncio

    print("🎯 Running example: Single infographic")
    asyncio.run(example_single_infographic())

    print("\n🎯 Running example: Batch infographics")
    asyncio.run(example_batch_infographics())

    print("\n🎯 Running example: Style comparison")
    asyncio.run(example_style_comparison())
